#!/usr/bin/env python3
"""Generate the v0.3 repeated-audit LaTeX table from frozen verdicts."""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
INPUT = ROOT / "evidence/20260713T191740Z/verdicts.json"
OUTPUT = ROOT / "paper/v3/generated-repeated-audit-table.tex"
CONFIGS = (
    "naive",
    "governed",
    "arm_namespace",
    "arm_provenance",
    "arm_ttl",
    "arm_gate",
    "arm_raw",
)
CONFIG_LABELS = {
    "naive": r"\texttt{naive}",
    "governed": r"\texttt{governed}",
    "arm_namespace": r"\texttt{namespace}",
    "arm_provenance": r"\texttt{provenance}",
    "arm_ttl": r"\texttt{ttl}",
    "arm_gate": r"\texttt{gate}",
    "arm_raw": r"\texttt{raw}",
}
SCENARIO_LABELS = {
    "CB-VAL-001": "001 drift",
    "CB-VAL-002": "002 provenance",
    "CB-VAL-003": "003 scope bleed",
    "CB-VAL-004": "004 staleness",
    "CB-VAL-005": "005 recursion (natural)",
    "CB-VAL-006": "006 summarization",
    "CB-VAL-007": "007 control (retention)",
    "CB-VAL-008": "008 control (empty)",
    "CB-VAL-009": "009 recursion (seeded)",
}


def fail(message: str) -> None:
    raise SystemExit(f"error: {message}")


def load_cells() -> dict[tuple[str, str], list[dict]]:
    try:
        document = json.loads(INPUT.read_text())
    except (OSError, json.JSONDecodeError) as error:
        fail(f"cannot read {INPUT}: {error}")
    if not isinstance(document, dict) or not isinstance(document.get("verdicts"), list):
        fail("expected a JSON object with a verdicts list")

    records = document["verdicts"]
    expected_total = len(SCENARIO_LABELS) * len(CONFIGS) * 5
    if len(records) != expected_total:
        fail(f"expected exactly {expected_total} execution records, found {len(records)}")

    cells: dict[tuple[str, str], list[dict]] = defaultdict(list)
    for record in records:
        if not isinstance(record, dict):
            fail("every verdict record must be an object")
        scenario = record.get("scenario_id")
        config = record.get("config_name")
        repetition = record.get("repetition")
        if scenario not in SCENARIO_LABELS:
            fail(f"unexpected scenario: {scenario!r}")
        if config not in CONFIGS:
            fail(f"unexpected config: {config!r}")
        if not isinstance(repetition, int) or repetition not in range(1, 6):
            fail(f"unexpected repetition for {scenario}/{config}: {repetition!r}")
        rounds = record.get("rounds")
        if not isinstance(rounds, list) or not rounds:
            fail(f"missing rounds for {scenario}/{config}/repetition-{repetition}")
        for round_record in rounds:
            if not isinstance(round_record, dict) or round_record.get("resolved") not in {
                "clean", "contaminated", "needs_human_review",
            }:
                fail(f"unexpected resolved verdict for {scenario}/{config}/repetition-{repetition}")
        cells[(scenario, config)].append(record)

    if {record["config_name"] for record in records} != set(CONFIGS):
        fail("frozen data do not contain exactly the seven required configs")
    return cells


def clean_count(records: list[dict], scenario: str, config: str) -> int:
    if len(records) != 5:
        fail(f"{scenario}/{config} has {len(records)} outcomes; expected exactly five")
    repetitions = sorted(record["repetition"] for record in records)
    if repetitions != [1, 2, 3, 4, 5]:
        fail(f"{scenario}/{config} has unexpected repetitions: {repetitions}")
    # An execution is clean only if every scored round resolves clean. This
    # keeps CB-VAL-005's two rounds within its single repetition-level outcome.
    return sum(
        all(round_record["resolved"] == "clean" for round_record in record["rounds"])
        for record in records
    )


def main() -> None:
    cells = load_cells()
    lines = [
        "% Generated by scripts/generate_repeated_audit_table.py from",
        "% evidence/20260713T191740Z/verdicts.json; do not hand-edit.",
        r"\begin{table}[p]",
        r"\centering",
        r"\scriptsize",
        r"\setlength{\tabcolsep}{3pt}",
        r"\begin{tabular}{@{}lccccccc@{}}",
        r"\toprule",
        "Scenario & " + " & ".join(CONFIG_LABELS[config] for config in CONFIGS) + r" \\",
        r"\midrule",
    ]
    for scenario, label in SCENARIO_LABELS.items():
        counts = [f"{clean_count(cells[(scenario, config)], scenario, config)}/5" for config in CONFIGS]
        lines.append(label + " & " + " & ".join(counts) + r" \\")
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            r"\caption{Frozen v0.3 repeated-audit clean outcomes. Every cell is",
            r"the number of clean resolved executions out of five repetitions (\(k/5\)).",
            r"An execution is clean only when all of its scored rounds resolve clean;",
            r"thus unresolved rounds count toward the denominator but are not clean.",
            r"These within-scenario results are descriptive (\(n=5\) per cell) and do",
            r"not support significance claims.}",
            r"\label{tab:repeated-audit}",
            r"\end{table}",
            "",
        ]
    )
    OUTPUT.write_text("\n".join(lines))


if __name__ == "__main__":
    main()
